#!/usr/bin/env python3

import subprocess
import threading
import argparse

#This function runs a baselisten command with relevant args
#"--serial /dev/ttyACM0" indicates the serial device to use is a USB port.
def listen(serial):
    subprocess.run(["baselisten", "--serial", serial])

def send():    
    while(1):
        data=input()
        subprocess.run(["send_string", data])
        
            

if __name__ == '__main__':

    parser = argparse.ArgumentParser(description='Combines separate write and read programs for the CLI')
    parser.add_argument('--serial', type=str, default="/dev/ttyACM0", help='Serial device to connect to.')

    args = parser.parse_args()
    serial = vars(args)['serial']

    listener = threading.Thread(target=listen, args = [serial]).start()
    sender = threading.Thread(target=send).start()

    print('did main')


# #Other Noteworthy methods

# p = subprocess.Popen('ls', shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
# for line in p.stdout.readlines():
#     print line,
# retval = p.wait()

